services:
  - type: web
    name: streamv11
    env: node
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: COOKIE_SECRET
        generateValue: true
      - key: DATA_DIR
        value: /tmp/data
    healthCheckPath: /api/health
